export interface SymbolicScar {
  id: string;
  timestamp: string;
  eventType: 'FAILED_NLI_CONTRADICTION' | 'EPISTEMIC_DRIFT' | 'PARSING_FAULT';
  mutationRecoverabilityScore: number;
  rawError: any;
}

/**
 * Controlled Scar Annealing Protocol (CSAP)
 * Logs and manages symbolic scars generated by paraconsistent overlaps or contradictions.
 * Scars with high MRS (Mutation Recoverability Score) are pruned/annealed, while low MRS scars
 * remain to induce 'Beneficial Friction'.
 */
export function logSymbolicScar(eventType: SymbolicScar['eventType'], rawError: any, mrs: number = 0.5): SymbolicScar | null {
  console.log(`[CSAP] Logging Symbolic Scar: ${eventType} with MRS ${mrs}`);

  const scar: SymbolicScar = {
    id: `scar-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    timestamp: new Date().toISOString(),
    eventType,
    mutationRecoverabilityScore: mrs,
    rawError
  };

  try {
    if (typeof window !== 'undefined' && window.localStorage) {
      const existingScars = JSON.parse(localStorage.getItem('symbolic_scars') || '[]');

      // Annealing logic: prune scars with MRS > 0.8
      const annealedScars = existingScars.filter((s: SymbolicScar) => s.mutationRecoverabilityScore <= 0.8);

      if (scar.mutationRecoverabilityScore <= 0.8) {
        annealedScars.push(scar);
      }

      localStorage.setItem('symbolic_scars', JSON.stringify(annealedScars));
    }
  } catch (e) {
    console.warn("Failed to persist symbolic scar:", e);
  }

  return scar;
}

/**
 * Parses and interprets errors generated by the AI reasoning engine or deterministic mathematical computation engines.
 * Acts as a translation layer between raw HTTP/Network errors or parsing failures and user-friendly UI strings.
 *
 * @param {unknown} err - The raw error object thrown during API interaction or symbol parsing.
 * @returns {string} A user-friendly, domain-specific error message detailing the failure mode.
 */
export function parseAIError(err: unknown): string {
  console.error("AI Analysis Error:", err);
  
  if (!err) return 'An unknown error occurred.';

  type ErrorShape = {
    status?: unknown;
    message?: unknown;
    response?: {
      status?: unknown;
      data?: {
        error?: {
          message?: unknown;
        };
      };
    };
  };

  const errObj = (typeof err === 'object' && err !== null ? err : {}) as ErrorShape;
  const rawStatus = errObj.status || errObj.response?.status;
  const status = typeof rawStatus === 'number' ? rawStatus : undefined;
  const rawMessage = errObj.message || errObj.response?.data?.error?.message;
  const message = typeof rawMessage === 'string' ? rawMessage : (err instanceof Error ? err.message : '');

  // Detect and log contradiction/NLI failures via CSAP
  if (message.includes('contradiction') || message.includes('NLI')) {
    logSymbolicScar('FAILED_NLI_CONTRADICTION', err, 0.4); // Low MRS to preserve beneficial friction
    return `Logical Contradiction Detected (FAILED_NLI_CONTRADICTION). Parallax zone recorded as Symbolic Scar.`;
  }

  if (message.includes('nerdamer') || message.includes('mathjs') || message.includes('parse error') || message.includes('simplification')) {
    logSymbolicScar('PARSING_FAULT', err, 0.85); // High MRS, likely to be annealed
    return `Deterministic Parsing Error: ${message}. The symbolic engine could not evaluate the expression.`;
  }

  if (status === 429 || message.includes('429') || message.includes('quota') || message.includes('rate limit')) {
    return 'Rate limit exceeded or quota exhausted. Please wait a moment and try again.';
  }
  
  if (status === 401 || status === 403 || message.includes('API key') || message.includes('authentication')) {
    return 'Authentication failed. Please check your Gemini API key configuration.';
  }
  
  if (status === 500 || status === 503 || message.includes('503') || message.includes('overloaded')) {
    return 'The AI service is currently overloaded or unavailable. Please try again later.';
  }
  
  if (message.includes('JSON') || message.includes('parse')) {
    return 'The model returned an invalid response format. Please try again.';
  }
  
  if (message.includes('fetch') || message.includes('network')) {
    return 'Network error. Please check your internet connection.';
  }

  return `Analysis failed: ${message || 'Unexpected error'}`;
}
