/**
 * Represents an unresolvable contradiction or error mapped as a "Symbolic Scar".
 */
export interface SymbolicScar {
  id: string;
  timestamp: string;
  eventType: 'FAILED_NLI_CONTRADICTION' | 'EPISTEMIC_DRIFT' | 'PARSING_FAULT';
  mutationRecoverabilityScore: number;
  rawError: any;
}

/**
 * Controlled Scar Annealing Protocol (CSAP)
 * Logs and manages symbolic scars generated by paraconsistent overlaps or contradictions.
 * Scars with high MRS (Mutation Recoverability Score) are pruned/annealed, while low MRS scars
 * remain to induce 'Beneficial Friction'.
 */
export function logSymbolicScar(eventType: SymbolicScar['eventType'], rawError: any, mrs: number = 0.5): SymbolicScar | null {
  console.log(`[CSAP] Logging Symbolic Scar: ${eventType} with MRS ${mrs}`);

  const scar: SymbolicScar = {
    id: `scar-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    timestamp: new Date().toISOString(),
    eventType,
    mutationRecoverabilityScore: mrs,
    rawError
  };

  try {
    if (typeof window !== 'undefined' && window.localStorage) {
      const existingScars = JSON.parse(localStorage.getItem('symbolic_scars') || '[]');

      // Annealing logic: prune scars with MRS > 0.8
      const annealedScars = existingScars.filter((s: SymbolicScar) => s.mutationRecoverabilityScore <= 0.8);

      if (scar.mutationRecoverabilityScore <= 0.8) {
        // If it's a contradiction payload, let's also save it to the escrow store
        if (eventType === 'FAILED_NLI_CONTRADICTION' && rawError && rawError.crs !== undefined) {
           const existingEscrow = JSON.parse(localStorage.getItem('epistemic_escrow') || '[]');
           existingEscrow.push(rawError);
           localStorage.setItem('epistemic_escrow', JSON.stringify(existingEscrow));
        }

        annealedScars.push(scar);
      }

      localStorage.setItem('symbolic_scars', JSON.stringify(annealedScars));
    }
  } catch (e) {

    console.warn("Failed to persist symbolic scar:", e);
  }

  return scar;
}

const CONTRADICTION_REGEX = /contradiction|NLI/;
const PARSING_FAULT_REGEX = /nerdamer|mathjs|parse error|simplification/;
const RATE_LIMIT_REGEX = /429|quota|rate limit/;
const AUTH_REGEX = /API key|authentication/;
const OVERLOADED_REGEX = /503|overloaded/;
const JSON_REGEX = /JSON|parse/;
const NETWORK_REGEX = /fetch|network/;

/**
 * Parses and interprets errors generated by the AI reasoning engine or deterministic mathematical computation engines.
 * Acts as a translation layer between raw HTTP/Network errors or parsing failures and user-friendly UI strings.
 *
 * @param {unknown} err - The raw error object thrown during API interaction or symbol parsing.
 * @returns {string} A user-friendly, domain-specific error message detailing the failure mode.
 */
export function parseAIError(err: unknown): string {
  console.error("AI Analysis Error:", err);
  
  if (!err) return 'An unknown error occurred.';

  type ErrorShape = {
    status?: unknown;
    message?: unknown;
    response?: {
      status?: unknown;
      data?: {
        error?: {
          message?: unknown;
        };
      };
    };
  };

  const errObj = (typeof err === 'object' && err !== null ? err : {}) as ErrorShape;
  const rawStatus = errObj.status || errObj.response?.status;
  const status = typeof rawStatus === 'number' ? rawStatus : undefined;
  const rawMessage = errObj.message || errObj.response?.data?.error?.message;
  const message = typeof rawMessage === 'string' ? rawMessage : (err instanceof Error ? err.message : '');

  // Detect and log contradiction/NLI failures via CSAP
  if (CONTRADICTION_REGEX.test(message)) {
    logSymbolicScar('FAILED_NLI_CONTRADICTION', err, 0.4); // Low MRS to preserve beneficial friction
    return `Logical Contradiction Detected (FAILED_NLI_CONTRADICTION). Parallax zone recorded as Symbolic Scar.`;
  }

  if (PARSING_FAULT_REGEX.test(message)) {
    logSymbolicScar('PARSING_FAULT', err, 0.85); // High MRS, likely to be annealed
    return `Deterministic Parsing Error: ${message}. The symbolic engine could not evaluate the expression.`;
  }

  if (status === 429 || RATE_LIMIT_REGEX.test(message)) {
    return 'Rate limit exceeded or quota exhausted. Please wait a moment and try again.';
  }
  
  if (status === 401 || status === 403 || AUTH_REGEX.test(message)) {
    return 'Authentication failed. Please check your Gemini API key configuration.';
  }
  
  if (status === 500 || status === 503 || OVERLOADED_REGEX.test(message)) {
    return 'The AI service is currently overloaded or unavailable. Please try again later.';
  }
  
  if (JSON_REGEX.test(message)) {
    return 'The model returned an invalid response format. Please try again.';
  }
  
  if (NETWORK_REGEX.test(message)) {
    return 'Network error. Please check your internet connection.';
  }

  return `Analysis failed: ${message || 'Unexpected error'}`;
}
